version: '2'
services:
  mongodb:
    image: "mongo"
    expose:
      - "27017"
    volumes:
      - ./mongodb:/data/db
      - ./Logs:/Logs
    environment:
      - MONGO_LOG_DIR=/Logs/db.log
    command: ["sh", "-c",  "mongod --smallfiles --quiet --bind_ip_all 1>/dev/null 2>> /Logs/db.log"]
    restart: always
  node:
    build: "./node/"
    ports:
      - "80:8080"
    volumes:
      - ./ModRank:/Modrank
      - ./Logs:/Logs
    depends_on:
      - mongodb
    restart: always
#  react:
#    build: ./react/
#    ports:
#      - "80:3000"
#    volumes:
#      - ./react:/opt/ModRank
#    depends_on:
#      - backend